#!/bin/sh

ROOT_DIR="$(cd "$(dirname "$0")" && cd .. && pwd)"

FILE_PATTERN="^\(axgl\|demo\|impl\|lib\).*\\.\(cpp\|hpp\|vs\|fs\)$"
FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -e "$FILE_PATTERN" | tr '\n' ' ')

sh "$ROOT_DIR/_scripts/format.sh" --files $FILES
if [ $? -ne 0 ]; then
  echo "Formatting failed! Aborting commit."
  exit 1
fi

git add $FILES
