#! /bin/sh

FILE_PATTERN="^\(axgl\|demo\|impl\|lib\).*\\.\(cpp\|hpp\)$"
FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -e "$FILE_PATTERN" | tr '\n' ' ')

clang-format -i $FILES
git add $FILES
