#pragma once

#define BASE_EVENT_TYPE 0

#define EVENT_TYPE_WINDOW_EVENT_BASE (BASE_EVENT_TYPE + 1)
#define EVENT_TYPE_WINDOW_KEYDOWN EVENT_TYPE_WINDOW_EVENT_BASE
#define EVENT_TYPE_WINDOW_KEYUP (EVENT_TYPE_WINDOW_KEYDOWN + 1)
#define EVENT_TYPE_WINDOW_MOUSEDOWN (EVENT_TYPE_WINDOW_KEYUP + 1)
#define EVENT_TYPE_WINDOW_MOUSEUP (EVENT_TYPE_WINDOW_MOUSEDOWN + 1)
#define EVENT_TYPE_WINDOW_MOUSEMOVE (EVENT_TYPE_WINDOW_MOUSEUP + 1)
#define EVENT_TYPE_WINDOW_RESIZE (EVENT_TYPE_WINDOW_MOUSEMOVE + 1)
#define EVENT_TYPE_WINDOW_END EVENT_TYPE_WINDOW_RESIZE

#define EVENT_TYPE_SEND_NETWORK_MESSAGE (EVENT_TYPE_WINDOW_END + 1)

