dictionaries = ["en_gb", "en_us"]
words = [
    "allman",
    "asio",
    "assbin",
    "assimp",
    "axgl",
    "bitangent",
    "bitangents",
    "blinn",
    "blit",
    "bugprone",
    "bundlefile",
    "clangd",
    "clearcoat",
    "cmake",
    "codegen",
    "cpptrace",
    "cubemap",
    "embedfile",
    "endforeach",
    "endfunction",
    "flatbuffer",
    "flatbuffers",
    "flatc",
    "fontface",
    "framebuffer",
    "freetype",
    "gameloop",
    "glfw",
    "imgui",
    "infacing",
    "inout",
    "lightmap",
    "metalness",
    "msaa",
    "msvc",
    "mswsock",
    "multisample",
    "opengl",
    "orthogonalize",
    "perlin",
    "phong",
    "renderable",
    "renderbuffer",
    "shader",
    "shaderiv",
    "skybox",
    "spdlog",
    "stbi",
    "stdlib",
    "ubyte",
    "unrenderable",
    "utfcpp",
]
ignore_paths = [
    ".git/**/*",
    ".vscode/**/*",
    ".codebook.toml",
    ".clang-tidy",
    "_log/**/*",
    "_build/**/*",
    "_external/**/*",
    "lib/glad/**/*",
]
ignore_patterns = [
    '\bgl[A-Z][a-zA-Z0-9]*\b',
    '\bGL_[A-Z0-9_]+\b',
    '\bglfw[A-Z][a-zA-Z0-9]*\b',
    '\bGLFW_[A-Z0-9_]+\b',
]

[[overrides]]
paths = ["_scripts/format.sh"]
words = ["regextype"]

[[overrides]]
paths = [
    "**/CMakePresets.json",
    "**/CMakeLists.txt",
    "**/*.cmake",
]
extra_words = [
    "argn",
    "strequal",
    "unittests",
]

[[overrides]]
paths = ["**/*.fbs"]
extra_words = [
    "bndl",
    "mesg",
]

[[overrides]]
paths = [
    "**/*.fs",
    "**/*.vs",
]
extra_words = [
    "ivec",
    "texel",
    "isinf",
]

[[overrides]]
paths = [
    ".clangd"
]
extra_ignore_patterns = [
    "[^a-zA-Z0-9]-[D|W|f][a-zA-Z0-9-]*",
]
