#! /bin/sh

DIR="$(cd "$(dirname "$0")" && pwd)"

# configure
cmake \
  -DGLFW_BUILD_DOCS=OFF \
  -DFLATBUFFERS_BUILD_TESTS=OFF \
  -DFLATBUFFERS_INSTALL=OFF \
  -DCPPTRACE_BUILD_TESTING=OFF \
  -DARGS_BUILD_EXAMPLE=OFF \
  -DARGS_BUILD_UNITTESTS=OFF \
  -DASSIMP_BUILD_TESTS=OFF \
  -DASSIMP_INSTALL=OFF \
  -B $DIR/../_build
