#pragma once

#define NAMESPACE_AXGL namespace axgl {
#define NAMESPACE_AXGL_END }

#define NAMESPACE_WORLD NAMESPACE_AXGL namespace world {
#define NAMESPACE_WORLD_END } NAMESPACE_AXGL_END

#define NAMESPACE_OPENGL NAMESPACE_AXGL namespace opengl {
#define NAMESPACE_OPENGL_END } NAMESPACE_AXGL_END
