#pragma once

#define NAMESPACE_AXGL namespace axgl {
#define NAMESPACE_AXGL_END }

#define NAMESPACE_WORLD NAMESPACE_AXGL namespace world {
#define NAMESPACE_WORLD_END } NAMESPACE_AXGL_END

#define NAMESPACE_GLFW NAMESPACE_AXGL namespace glfw {
#define NAMESPACE_GLFW_END } NAMESPACE_AXGL_END

#define NAMESPACE_OPENGL NAMESPACE_AXGL namespace opengl {
#define NAMESPACE_OPENGL_END } NAMESPACE_AXGL_END

#define NAMESPACE_OPENGL_SHADER NAMESPACE_OPENGL namespace shader {
#define NAMESPACE_OPENGL_SHADER_END } NAMESPACE_OPENGL_END

#define NAMESPACE_OPENGL_ENTITY NAMESPACE_OPENGL namespace entity {
#define NAMESPACE_OPENGL_ENTITY_END } NAMESPACE_OPENGL_END
